project:
  type: website

website:
  title: "osm-cca"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd
  sidebar:
#    style: "docked"
    style: "floating"
    collapse-level: 3
    search: true
    contents:
      - text: "course start"
        href: index.qmd
      - section: "module 1"
        href: module01-understanding-sustainability-communication-content-10pct/index.qmd
        contents:
          - text: "lesson 1.1"
            href: module01-understanding-sustainability-communication-content-10pct/1-1-lesson.qmd
            contents:
              - text: "lecture 1.1.1"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-1-video-lecture.qmd
              - text: "computer lab 1.1.2"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-2-computer-lab.qmd
              - text: "computer lab 1.1.3"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-3-computer-lab.qmd
      - section: "module 2"
        href: module02-introduction-to-low-code-python-programming-20pct/index.qmd
        contents:
          - text: "lesson 2.1"
            href: module02-introduction-to-low-code-python-programming-20pct/2-1-lesson.qmd
            contents:
              - text: "lecture 2.1.1"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-1-video-lecture.qmd
              - text: "computer lab 2.1.2"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-2-computer-lab.qmd
              - text: "computer lab 2.1.3"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-3-computer-lab.qmd
          - text: "lesson 2.2"
            href: module02-introduction-to-low-code-python-programming-20pct/2-2-lesson.qmd
            contents:
              - text: "lecture 2.2.1"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-1-video-lecture.qmd
              - text: "computer lab 2.2.2"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-2-computer-lab.qmd
              - text: "computer lab 2.2.3"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-3-computer-lab.qmd
      - section: "module 3"
        href: module03-analyzing-text-content-natural-language-processing-30pct/index.qmd
        contents:
          - text: "lesson 3.1"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-lesson.qmd
            contents:
              - text: "lecture 3.1.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-1-video-lecture.qmd
              - text: "computer lab 3.1.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-2-computer-lab.qmd
              - text: "computer lab 3.1.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-3-computer-lab.qmd
          - text: "lesson 3.2"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-lesson.qmd
            contents:
              - text: "lecture 3.2.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-1-video-lecture.qmd
              - text: "computer lab 3.2.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-2-computer-lab.qmd
              - text: "computer lab 3.2.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-3-computer-lab.qmd
          - text: "lesson 3.3"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-lesson.qmd
            contents:
              - text: "lecture 3.3.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-1-video-lecture.qmd
              - text: "computer lab 3.3.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-2-computer-lab.qmd
              - text: "computer lab 3.3.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-3-computer-lab.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



