execute:
#  eval 	Evaluate the code chunk (if false, just echos the code into the output).
  eval: false
#  echo 	Include the source code in output
  echo: true
#  output 	Include the results of executing the code in the output (true, false, or asis to indicate that the output is raw markdown and should not have any of Quarto’s standard enclosing markdown).
  output: false
#  warning 	Include warnings in the output.
  warning: false
#  error 	Include errors in the output (note that this implies that errors executing code will not halt processing of the document).
  error: false
jupyter: python3

project:
  type: website

website:
  title: "osm-cca"
#  navbar:
#    left:
#      - href: index.qmd
#        text: Home
#      - about.qmd
  sidebar:
#    style: "docked"
    style: "floating"
    collapse-level: 3
    search: true
    contents:
      - text: "course start"
        href: index.qmd
      - section: "module 1"
        href: module01-understanding-sustainability-communication-content-10pct/index.qmd
        contents:
          - text: "lesson 1.1"
            href: module01-understanding-sustainability-communication-content-10pct/1-1-lesson.qmd
            contents:
              - text: "lecture 1.1.1"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-1-video-lecture.qmd
              - text: "computer lab 1.1.2"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-2-computer-lab.qmd
              - text: "computer lab 1.1.3"
                href: module01-understanding-sustainability-communication-content-10pct/1-1-3-computer-lab.qmd
      - section: "module 2"
        href: module02-introduction-to-low-code-python-programming-20pct/index.qmd
        contents:
          - text: "lesson 2.1"
            href: module02-introduction-to-low-code-python-programming-20pct/2-1-lesson.qmd
            contents:
              - text: "lecture 2.1.1"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-1-video-lecture.qmd
              - text: "computer lab 2.1.2"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-2-computer-lab.qmd
              - text: "computer lab 2.1.3"
                href: module02-introduction-to-low-code-python-programming-20pct/2-1-3-computer-lab.qmd
          - text: "lesson 2.2"
            href: module02-introduction-to-low-code-python-programming-20pct/2-2-lesson.qmd
            contents:
              - text: "lecture 2.2.1"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-1-video-lecture.qmd
              - text: "computer lab 2.2.2"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-2-computer-lab.qmd
              - text: "computer lab 2.2.3"
                href: module02-introduction-to-low-code-python-programming-20pct/2-2-3-computer-lab.qmd
      - section: "module 3"
        href: module03-analyzing-text-content-natural-language-processing-30pct/index.qmd
        contents:
          - text: "lesson 3.1"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-lesson.qmd
            contents:
              - text: "lecture 3.1.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-1-video-lecture.qmd
              - text: "computer lab 3.1.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-2-computer-lab.qmd
              - text: "computer lab 3.1.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-1-3-computer-lab.qmd
          - text: "lesson 3.2"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-lesson.qmd
            contents:
              - text: "lecture 3.2.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-1-video-lecture.qmd
              - text: "computer lab 3.2.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-2-computer-lab.qmd
              - text: "computer lab 3.2.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-2-3-computer-lab.qmd
          - text: "lesson 3.3"
            href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-lesson.qmd
            contents:
              - text: "lecture 3.3.1"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-1-video-lecture.qmd
              - text: "computer lab 3.3.2"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-2-computer-lab.qmd
              - text: "computer lab 3.3.3"
                href: module03-analyzing-text-content-natural-language-processing-30pct/3-3-3-computer-lab.qmd
      - section: "module 4"
        href: module04-analyzing-image-content-computer-vision-30pct/index.qmd
        contents:
          - text: "lesson 4.1"
            href: module04-analyzing-image-content-computer-vision-30pct/4-1-lesson.qmd
            contents:
              - text: "lecture 4.1.1"
                href: module04-analyzing-image-content-computer-vision-30pct/4-1-1-video-lecture.qmd
              - text: "computer lab 4.1.2"
                href: module04-analyzing-image-content-computer-vision-30pct/4-1-2-computer-lab.qmd
              - text: "computer lab 4.1.3"
                href: module04-analyzing-image-content-computer-vision-30pct/4-1-3-computer-lab.qmd
          - text: "lesson 4.2"
            href: module04-analyzing-image-content-computer-vision-30pct/4-2-lesson.qmd
            contents:
              - text: "lecture 4.2.1"
                href: module04-analyzing-image-content-computer-vision-30pct/4-2-1-video-lecture.qmd
              - text: "computer lab 4.2.2"
                href: module04-analyzing-image-content-computer-vision-30pct/4-2-2-computer-lab.qmd
              - text: "computer lab 4.2.3"
                href: module04-analyzing-image-content-computer-vision-30pct/4-2-3-computer-lab.qmd
          - text: "lesson 4.3"
            href: module04-analyzing-image-content-computer-vision-30pct/4-3-lesson.qmd
            contents:
              - text: "lecture 4.3.1"
                href: module04-analyzing-image-content-computer-vision-30pct/4-3-1-video-lecture.qmd
              - text: "computer lab 4.3.2"
                href: module04-analyzing-image-content-computer-vision-30pct/4-3-2-computer-lab.qmd
              - text: "computer lab 4.3.3"
                href: module04-analyzing-image-content-computer-vision-30pct/4-3-3-computer-lab.qmd
      - section: "module 5"
        href: module05-ethical-aspects-of-ai-aided-content-analysis-10pct/index.qmd
        contents:
          - text: "lesson 5.1"
            href: module05-ethical-aspects-of-ai-aided-content-analysis-10pct/5-1-lesson.qmd
            contents:
              - text: "lecture 5.1.1"
                href: module05-ethical-aspects-of-ai-aided-content-analysis-10pct/5-1-1-video-lecture.qmd
              - text: "computer lab 5.1.2"
                href: module05-ethical-aspects-of-ai-aided-content-analysis-10pct/5-1-2-computer-lab.qmd
              - text: "computer lab 5.1.3"
                href: module05-ethical-aspects-of-ai-aided-content-analysis-10pct/5-1-3-computer-lab.qmd

format:
  html:
#    theme: cosmo
    theme: darkly
    css: styles.css
    toc: true
#  pdf: 
#    documentclass: report
#    classoption: [twocolumn, landscape]
#    lof: true
#    lot: true
#    geometry:
#      - top=30mm
#      - left=20mm
#      - heightrounded
#    fontfamily: libertinus
#    colorlinks: true

bibliography: /home/sol-nhl/rnd/r/literature/bibs/sustainability-communication.bib
bibliographystyle: apa
