---
title: "web/ai-aided-content-analysis-of-sustainability-communication"
---

## overview of mooc course (ca 10 lessons x 3 hours work)

### check list for setting up screen recordings

#### video lecture
- open google chrome, access google isk account 
- go to [microsoft teams, stream web app](https://www.microsoft365.com/launch/stream?auth=2) 
- start screen recording of google slides browser tab
- start google slides in presenter view
- read presentation script, stop screen recording
- continue screen recording until done, finalize video

#### computer lab 
- open google chrome, access google isk account 
- go to [microsoft teams, stream web app](https://www.microsoft365.com/launch/stream?auth=2) 
- start screen recording of google colab browser tab
- execute jupyter notebook cells and explain, stop screen recording
- continue screen recording until done, finalize video

#### prepare quiz

---

This is a Quarto website.

To learn more about Quarto websites visit <https://quarto.org/docs/websites>.
